### ISSUE TITLE
Review 1

### ISSUE THREAD

**Issue by danielaciuperca** [Seras3/eTicket#1]
1. Please use camelCase for all identifiers (please refactor in all classes).
https://github.com/Seras3/eTicket/blob/be6f210dc842b676badcab09b336bece5eac4621/src/main/java/model/Account.java#L12
2. Why do you need this constructor if you put @AllArgConstructor on the class?
https://github.com/Seras3/eTicket/blob/be6f210dc842b676badcab09b336bece5eac4621/src/main/java/model/Account.java#L14
3. These classes are not services, they shouldn't be in the service package.
https://github.com/Seras3/eTicket/blob/be6f210dc842b676badcab09b336bece5eac4621/src/main/java/service/Identity.java#L4
https://github.com/Seras3/eTicket/blob/be6f210dc842b676badcab09b336bece5eac4621/src/main/java/service/Context.java#L3
4. This class should be named something like DatabaseConfig and should be placed in a package named config or configuration, not in service.
https://github.com/Seras3/eTicket/blob/be6f210dc842b676badcab09b336bece5eac4621/src/main/java/service/Database.java#L8
5. Why having this class, when you defined a DAO generic class? They seem pretty similar. And you should have only one package for dealing with the database operations, only dao or only repository. I suggest repository.
https://github.com/Seras3/eTicket/blob/be6f210dc842b676badcab09b336bece5eac4621/src/main/java/repository/Repository.java#L3
6. When you are working with collections, please use interface = new implementation() pattern. (for example here, please use Map instead of HashMap for the parameter). Please refactor this in all classes.
https://github.com/Seras3/eTicket/blob/be6f210dc842b676badcab09b336bece5eac4621/src/main/java/dao/AccountDAO.java#L34
7. Consider returning Optional.empty() instead of null, to avoid potential NPE.
https://github.com/Seras3/eTicket/blob/be6f210dc842b676badcab09b336bece5eac4621/src/main/java/dao/AccountDAO.java#L20
8. It's better to use PreparedStatement instead of Statement. You will be able to bind parameters by name or index and the performance will be better. More details here: https://www.baeldung.com/java-statement-preparedstatement
https://github.com/Seras3/eTicket/blob/be6f210dc842b676badcab09b336bece5eac4621/src/main/java/dao/AccountDAO.java#L55
9. It would be good the method names from the mapper to be something like authDtoToAccount().
https://github.com/Seras3/eTicket/blob/be6f210dc842b676badcab09b336bece5eac4621/src/main/java/mapper/AccountMapper.java#L13
10. You should have a service for each entity that you want to use. For example, API class contains now only methods related to events. This class should be EventService. If you want to have a main class, let's say API, this class should contain references to all entity services you need.
https://github.com/Seras3/eTicket/blob/be6f210dc842b676badcab09b336bece5eac4621/src/main/java/service/API.java#L13
11. Use equals() instead of ==.
https://github.com/Seras3/eTicket/blob/be6f210dc842b676badcab09b336bece5eac4621/src/main/java/scene/Scene.java#L35

**Comment by Seras3** [comment]
1.  ✔️ 
2.  In that case I don't use Account copy constructor but in some other cases I need a copy constructor for example : 
I have a base class Ticket and a derived SeatTicket. If I want a new SeatTicket with Ticket fields I need a copy constructor in Ticket class. ( It could be a better approach ? 🤔 ).
3. ✔️
4. ✔️
5.  I saw that template when I was reading about this topic but I changed it. You'll see in next commit.
6. ✔️ 
7.  I modified that function, but I'll consider this for next implementations.
8. ✔️ 
9. ✔️
10.  First I mix them in API, then I separate it in different components. ( It's first time when I  write an API, so I thought that's a safe approach. )
11. ✔️
